name: Build AllLive Windows
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装.NET8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # 还原整体解决方案
      - run: dotnet restore AllLive.sln

      # 完整编译所有项目，生成Release版exe（无独立运行时，框架冲突彻底消失）
      - run: dotnet build AllLive.sln -c Release --no-restore

      # 全局匹配所有编译输出的程序文件夹上传
      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: AllLive-Win-Build
          path: '**/bin/Release/**'
