name: Build AllLive Windows
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装.NET8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # 还原整个解决方案
      - run: dotnet restore AllLive.sln

      # 编译整个解决方案，不再指定单个csproj路径
      - run: dotnet build AllLive.sln -c Release --no-restore

      # 发布整个解决方案，主程序会自动生成windows包
      - run: dotnet publish AllLive.sln -c Release --self-contained true --no-build

      # 匹配所有publish文件夹上传
      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: AllLive-Win-x64
          path: '**/publish/**'
