name: Build AllLive Console SelfContained
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - run: dotnet restore AllLive.sln
      # 整体编译解决方案
      - run: dotnet build AllLive.sln -c Release --no-restore
      # 发布时指定win-x64自包含，只会给可执行程序打包，类库自动适配
      - run: dotnet publish AllLive.sln -c Release -r win-x64 --self-contained true --no-build

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: AllLive-Console-Win-Self
          path: AllLive.Console/bin/Release/net8.0/win-x64/publish
